name: Run Any Java File

on:
  workflow_dispatch:
    inputs:
      java_file:
        description: 'Path to the .java file in this repo'
        required: true
        default: 'src/J0915.java'
      input_data:
        description: 'Input for the program (use \n for new lines)'
        required: false
        default: "80\n90\n70\n-1"
      jdk:
        description: 'JDK version'
        required: false
        default: '17'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ github.event.inputs.jdk }}
          distribution: temurin

      - name: Show repo files
        run: ls -R

      - name: Compile selected file
        run: |
          mkdir -p build
          echo "Compiling ${{ github.event.inputs.java_file }}"
          javac -encoding UTF-8 -d build "${{ github.event.inputs.java_file }}"

      - name: Run compiled class
        run: |
          CLASS_NAME=$(basename "${{ github.event.inputs.java_file }}" .java)
          printf "%b" "${{ github.event.inputs.input_data }}" | java -cp build "$CLASS_NAME"
